
CREATE TABLE IF NOT EXISTS friends (
  user_id INTEGER,
  friend_id INTEGER,
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(100),
  login varchar(100),
  name varchar(100),
  birthday date
);

CREATE TABLE IF NOT EXISTS genres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS filmsGenres (
  film_id INTEGER,
  genre_id INTEGER,
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likesFromUsers (
  film_id INTEGER,
  user_id INTEGER,
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS mpa (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS films (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  description VARCHAR(100),
  releaseDate date,
  duration INTEGER,
  mpa_id INTEGER
);

ALTER TABLE friends ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE friends ADD FOREIGN KEY (friend_id) REFERENCES users (id);

ALTER TABLE filmsGenres ADD FOREIGN KEY (genre_id) REFERENCES genres (id);
ALTER TABLE filmsGenres ADD FOREIGN KEY (film_id) REFERENCES films (id);

ALTER TABLE likesFromUsers ADD FOREIGN KEY (film_id) REFERENCES films (id);
ALTER TABLE likesFromUsers ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE films ADD FOREIGN KEY (mpa_id) REFERENCES mpa (id);
